/*
 * Style-only design-sync converter for ryanlindsey.me.
 *
 * This repo has no React component library, so the stock /design-sync
 * converter has nothing to bundle (see .design-sync/NOTES.md). What it does
 * have is a real design language, and that is what this script ships: the
 * token layer, the type scale, the three families, and the utility vocabulary
 * that global.css declares.
 *
 * Everything is DERIVED from src/styles/*.css rather than transcribed. The
 * @theme inline block is parsed and the utility layer generated from it, so a
 * token added to global.css reaches the design system on the next run with no
 * edit here. Nothing in this file hardcodes a colour, a size or a family.
 *
 * Why a plain-CSS utility layer exists at all: rendered designs receive only
 * the styles.css @import closure. `@theme inline` is a Tailwind v4 build-time
 * construct, so if claude.ai/design does not compile this CSS through Tailwind
 * the namespaces never become classes and every `bg-surface` in a generated
 * design resolves to nothing -- silently. The generated layer makes the
 * vocabulary resolve without a build; the @theme block is still emitted so a
 * Tailwind-native pipeline maps the same names to the same values.
 */

import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(repo, 'src/styles');
const out = join(repo, 'ds-bundle');
const nm = join(repo, 'node_modules');

const globalCss = readFileSync(join(src, 'global.css'), 'utf8');

/* Brace-matched block extractor. `head` is matched literally at a line start. */
function block(css, head) {
  const start = css.indexOf(head);
  if (start === -1) throw new Error(`missing block: ${head}`);
  let i = css.indexOf('{', start);
  let depth = 0;
  for (let j = i; j < css.length; j++) {
    if (css[j] === '{') depth++;
    else if (css[j] === '}') {
      depth--;
      if (depth === 0) return { head: css.slice(start, i).trim(), body: css.slice(i + 1, j) };
    }
  }
  throw new Error(`unterminated block: ${head}`);
}

/* --- parse the theme contract ------------------------------------------- */

const theme = block(globalCss, '@theme inline');
const decls = [...theme.body.matchAll(/^\s*(--[\w-]+)\s*:\s*([^;]+);/gm)].map((m) => [
  m[1],
  m[2].trim(),
]);

const colors = [];
const fonts = [];
const sizes = new Map();

for (const [name, value] of decls) {
  let m;
  if ((m = name.match(/^--color-(.+)$/))) colors.push([m[1], value]);
  else if ((m = name.match(/^--font-(.+)$/))) fonts.push([m[1], value]);
  else if ((m = name.match(/^--text-([\w-]+?)--(.+)$/))) {
    if (!sizes.has(m[1])) sizes.set(m[1], {});
    sizes.get(m[1])[m[2]] = value;
  } else if ((m = name.match(/^--text-([\w-]+)$/))) {
    if (!sizes.has(m[1])) sizes.set(m[1], {});
    sizes.get(m[1])['font-size'] = value;
  }
}

const nameClash = colors.map(([n]) => n).filter((n) => sizes.has(n));
if (nameClash.length) throw new Error(`color/text name collision: ${nameClash.join(', ')}`);

/* --- emit ---------------------------------------------------------------- */

const banner = (what) =>
  `/* ${what}\n * Generated by .design-sync/build-styles.mjs from src/styles/. Do not edit here.\n */\n\n`;

mkdirSync(join(out, 'tokens'), { recursive: true });
mkdirSync(join(out, 'fonts/files'), { recursive: true });

/* 1. tokens.css travels verbatim: it is pure custom properties with no build
 *    dependency, so a copy cannot drift from what the site renders. */
copyFileSync(join(src, 'tokens.css'), join(out, 'tokens/tokens.css'));

/* 2. The Tailwind v4 contract, for pipelines that compile it. */
const variant = globalCss.match(/^@custom-variant dark \(.+\);$/m);
writeFileSync(
  join(out, 'tokens/theme.css'),
  banner('Tailwind v4 theme contract.') +
    '/* Only consumed when this CSS is compiled by Tailwind v4; inert otherwise,\n' +
    ' * which is why tokens/utilities.css exists alongside it. */\n\n' +
    `@theme inline {${theme.body}}\n\n` +
    (variant ? `${variant[0]}\n` : ''),
);

/* 2b. The theme values as REAL custom properties.
 *
 * Caught by the render check, not by reading: `@theme` is not a native at-rule,
 * so a browser skips the whole block and every `var(--font-mono)` resolves to
 * nothing -- the card rendered in Times before this file existed. Tailwind
 * emits these to :root itself, which is why the site has never needed it.
 *
 * Deliberately a superset of the built site's CSS: Tailwind tree-shakes the
 * theme down to the variables the site actually references (today only
 * --text-body and --text-micro survive), and a design system cannot, because
 * the agent may reference any of them. Colours are NOT emitted here -- the
 * site does not emit --color-* either, `inline` resolves those to var(--rl-*)
 * at build time, and tokens.css already declares the --rl-* layer natively. */
const cut = globalCss.match(/--rl-cut:\s*([^;]+);/);
writeFileSync(
  join(out, 'tokens/scale.css'),
  banner('Families, type scale and motion as native custom properties.') +
    ':root {\n' +
    fonts.map(([n, v]) => `  --font-${n}: ${v};`).join('\n') +
    '\n\n' +
    [...sizes.entries()]
      .map(([n, p]) =>
        Object.entries(p)
          .map(([k, v]) => `  --text-${n}${k === 'font-size' ? '' : `--${k}`}: ${v};`)
          .join('\n'),
      )
      .join('\n') +
    (cut ? `\n\n  --rl-cut: ${cut[1].trim()};` : '') +
    '\n}\n',
);

/* 3. The same vocabulary as plain CSS, so it resolves with no build step.
 *    Theme flipping needs no dark: variants here -- the utilities point at the
 *    --rl-* tokens, and tokens.css re-declares those per data-theme. */
let u = banner('Utility vocabulary, generated from the @theme inline block.');
u += '/* Colour. Every value is a token reference, so one data-theme flip re-themes\n';
u += ' * the whole design with no duplicate classes. */\n';
for (const [name, value] of colors) {
  u += `.bg-${name} { background-color: ${value}; }\n`;
  u += `.text-${name} { color: ${value}; }\n`;
  u += `.border-${name} { border-color: ${value}; }\n`;
}
u += '\n/* Families. */\n';
for (const [name, value] of fonts) u += `.font-${name} { font-family: ${value}; }\n`;

u += '\n/* Type scale. Line height, tracking and weight travel with the size, exactly\n';
u += ' * as the @theme block declares them. */\n';
for (const [name, props] of sizes) {
  const body = Object.entries(props)
    .map(([k, v]) => `${k}: ${v};`)
    .join(' ');
  u += `.text-${name} { ${body} }\n`;
}

/* prose-rl: faithful copy of the @utility block, plus a zero-specificity
 * fallback so article prose still reads correctly when @tailwindcss/typography
 * is absent. :where() keeps it at (0,0,0) so the real plugin always wins. */
const prose = block(globalCss, '@utility prose-rl');
u += `\n/* Article prose wrapper. */\n.prose-rl {${prose.body}}\n`;
u += `
/* Standalone fallback: the --tw-prose-* values above only do anything when
 * @tailwindcss/typography is in the pipeline. These rules apply the same token
 * values directly so prose is not unstyled without it. */
.prose-rl :where(a) { color: var(--tw-prose-links); text-underline-offset: 2px; }
.prose-rl :where(strong) { color: var(--tw-prose-bold); }
.prose-rl :where(hr) { border-color: var(--tw-prose-hr); }
.prose-rl :where(blockquote) { border-inline-start: 2px solid var(--tw-prose-quote-borders); padding-inline-start: 1rem; color: var(--tw-prose-quotes); }
.prose-rl :where(li)::marker { color: var(--tw-prose-bullets); }
.prose-rl :where(code) { color: var(--tw-prose-code); font-family: var(--font-mono); }
.prose-rl :where(th) { border-color: var(--tw-prose-th-borders); }
.prose-rl :where(td) { border-color: var(--tw-prose-td-borders); }
.prose-rl :where(figcaption) { color: var(--tw-prose-captions); }
`;
writeFileSync(join(out, 'tokens/utilities.css'), u);

/* 4. Element defaults. Native @layer, so this needs no build step either. */
const base = block(globalCss, '@layer base');
writeFileSync(
  join(out, 'tokens/base.css'),
  banner('Element defaults.') + `@layer base {${base.body}}\n`,
);

/* 5. Fonts. Bare @fontsource specifiers cannot resolve in the design runtime,
 *    so the faces are copied in and the @font-face rules rewritten to relative
 *    URLs. Latin and latin-ext only: the site's own justification for the
 *    subset split applies here too, and the design runtime is latin. */
const faces = [
  [
    '@fontsource-variable/inter',
    'opsz.css',
    ['inter-latin-opsz-normal', 'inter-latin-ext-opsz-normal'],
  ],
  [
    '@fontsource-variable/space-grotesk',
    'wght.css',
    ['space-grotesk-latin-wght-normal', 'space-grotesk-latin-ext-wght-normal'],
  ],
  ['@fontsource/ibm-plex-mono', 'latin-400.css', ['ibm-plex-mono-latin-400-normal']],
  ['@fontsource/ibm-plex-mono', 'latin-600.css', ['ibm-plex-mono-latin-600-normal']],
];

let fontCss = banner('Font faces, copied from the Fontsource packages in node_modules.');
for (const [pkg, cssFile, wanted] of faces) {
  const sheet = readFileSync(join(nm, pkg, cssFile), 'utf8');
  for (const face of wanted) {
    const b = block(sheet, `/* ${face} */`);
    // Keep woff2 only; drop the legacy woff alternate some packages list.
    let rules = b.body
      .replace(
        /src:[^;]+;/,
        `src: url('./files/${face}.woff2') format('${face.includes('-wght-') || face.includes('-opsz-') ? 'woff2-variations' : 'woff2'}');`,
      )
      .trim();
    fontCss += `/* ${face} */\n@font-face {\n  ${rules.replace(/\n\s*/g, '\n  ')}\n}\n\n`;
    copyFileSync(join(nm, pkg, 'files', `${face}.woff2`), join(out, `fonts/files/${face}.woff2`));
  }
}
writeFileSync(join(out, 'fonts/fonts.css'), fontCss);

/* 6. The entry. Order mirrors global.css: faces first, then tokens, then the
 *    contract, then utilities, then element defaults. Rendered designs get
 *    this closure and nothing else, so everything real must be reachable here. */
writeFileSync(
  join(out, 'styles.css'),
  `/*
 * ryanlindsey.me design language -- entry point.
 *
 * Rendered designs receive only this file's transitive @import closure, so
 * every token, face and class the design agent is told about is reachable
 * from here.
 */
@import './fonts/fonts.css';
@import './tokens/tokens.css';
@import './tokens/scale.css';
@import './tokens/theme.css';
@import './tokens/utilities.css';
@import './tokens/base.css';
`,
);

/* 7. A well-formed but empty bundle. The app's self-check expects
 *    _ds_bundle.js at the root; there are no React components to put in it,
 *    and inventing some would ship a library this repo does not have. */
const header = JSON.stringify({
  namespace: 'RLME',
  components: [],
  sourceHashes: {},
  inlinedExternals: [],
  builtBy: 'cc-design-sync',
});
writeFileSync(
  join(out, '_ds_bundle.js'),
  `/* @ds-bundle: ${header} */\n` +
    `"use strict";(function(){window.RLME=window.RLME||{};})();\n` +
    `/* Style-only sync: this design system ships a token and type layer, not\n` +
    ` * React components. See README.md. */\n`,
);

writeFileSync(join(out, '_ds_needs_recompile'), JSON.stringify({ by: 'design-sync-cli' }));

/* 8. Foundation cards. Not components -- this repo has none -- but the pane
 *    indexes any preview HTML carrying a first-line @dsCard marker, and a
 *    palette and a type scale are worth more there than an empty shell. Both
 *    are generated from the parsed theme, and both load the real styles.css
 *    closure, so a card that renders correctly is evidence the closure works. */
function card(name, body) {
  const dir = join(out, 'components/Foundations', name);
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    join(dir, `${name}.html`),
    `<!-- @dsCard group="Foundations" -->
<!doctype html>
<meta charset="utf-8" />
<title>${name}</title>
<link rel="stylesheet" href="../../../styles.css" />
<style>
  body { margin: 0; padding: 2rem; background: var(--rl-bg); color: var(--rl-ink); }
  .pair { display: grid; grid-template-columns: 1fr 1fr; gap: 0; }
  .pane { padding: 2rem; background: var(--rl-bg); color: var(--rl-ink); }
  h1 { font-family: var(--font-display); font-size: var(--text-heading); letter-spacing: -0.02em; margin: 0 0 1.5rem; }
  .label { font-family: var(--font-mono); font-size: var(--text-micro); letter-spacing: 0.06em; text-transform: uppercase; color: var(--rl-ink-muted); }
</style>
${body}
`,
  );
}

const swatches = colors
  .map(
    ([n, v]) => `    <div>
      <div style="height:3.5rem;background:${v};border:1px solid var(--rl-rule)"></div>
      <div class="label" style="margin-top:.4rem">${n}</div>
    </div>`,
  )
  .join('\n');

card(
  'Color',
  `<div class="pair">
  <div class="pane" data-theme="light">
    <h1>Light</h1>
    <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:1rem">
${swatches}
    </div>
  </div>
  <div class="pane" data-theme="dark">
    <h1>Dark</h1>
    <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:1rem">
${swatches}
    </div>
  </div>
</div>`,
);

/* 9. README = the hand-authored conventions header, then a generated index.
 *    The header is what reaches the design agent's system prompt, so it leads. */
const headerPath = join(repo, '.design-sync/conventions.md');
const readmeHeader = readFileSync(headerPath, 'utf8').trimEnd();
const classList = [
  ...colors.flatMap(([n]) => [`bg-${n}`, `text-${n}`, `border-${n}`]),
  ...fonts.map(([n]) => `font-${n}`),
  ...[...sizes.keys()].map((n) => `text-${n}`),
  'prose-rl',
];
writeFileSync(
  join(out, 'README.md'),
  `${readmeHeader}

---

## What is in this bundle

Generated from \`src/styles/\` of the ryanlindsey.me repository. Every value is derived from that source rather than transcribed, so nothing here can drift from what the site renders.

| Path | Holds |
| --- | --- |
| \`styles.css\` | the entry point, and the only file a rendered design needs to import |
| \`tokens/tokens.css\` | the \`--rl-*\` palette for light, dark, the no-JavaScript path and print |
| \`tokens/scale.css\` | families, the type scale and the motion constant as native custom properties |
| \`tokens/theme.css\` | the Tailwind v4 \`@theme inline\` contract, for pipelines that compile it |
| \`tokens/utilities.css\` | the ${classList.length} utility classes, as plain CSS |
| \`tokens/base.css\` | element defaults, focus, selection and reduced motion |
| \`fonts/\` | ${faces.reduce((n, f) => n + f[2].length, 0)} woff2 faces and their \`@font-face\` rules |
| \`components/Foundations/\` | palette and type specimen cards |

## The complete class list

\`\`\`
${classList.join('\n')}
\`\`\`

## There are no components

The source repository is an Astro content site, not a component library, so there is nothing to compile into \`_ds_bundle.js\` and it is deliberately empty. Build controls yourself and style them with the vocabulary above.
`,
);

const specimens = [...sizes.entries()]
  .map(
    ([n, p]) => `  <div style="margin-bottom:1.75rem">
    <div class="label">text-${n} &middot; ${p['font-size']}</div>
    <div class="text-${n}" style="font-family:${n === 'body' || n === 'small' ? 'var(--font-sans)' : 'var(--font-display)'}">Flat bright color as signal</div>
  </div>`,
  )
  .join('\n');

card(
  'Typography',
  `<div>
  <h1>Type scale</h1>
${specimens}
  <div style="margin-top:2.5rem;border-top:1px solid var(--rl-rule);padding-top:1.5rem">
    <div class="label">families</div>
    <div class="font-display" style="font-size:var(--text-subheading);margin-top:.5rem">font-display &mdash; Space Grotesk Variable</div>
    <div class="font-sans" style="font-size:var(--text-subheading)">font-sans &mdash; Inter Variable</div>
    <div class="font-mono" style="font-size:var(--text-subheading)">font-mono &mdash; IBM Plex Mono</div>
  </div>
</div>`,
);

console.log(
  JSON.stringify(
    {
      colors: colors.length,
      fonts: fonts.length,
      textSizes: sizes.size,
      faces: faces.reduce((n, f) => n + f[2].length, 0),
      colorNames: colors.map(([n]) => n),
      textNames: [...sizes.keys()],
      fontNames: fonts.map(([n]) => n),
    },
    null,
    2,
  ),
);
