import { createMcpHandler } from 'agents/mcp/server';
import { McpServer } from '@modelcontextprotocol/server';
import { corpusRefreshEnabled, refreshCorpus, type CorpusEnv } from '../../../src/lib/corpus';

/**
 * This Worker's bindings.
 *
 * `Env` is generated by `wrangler types`, which reads ./wrangler.jsonc -- the
 * SITE's config -- so it is not this Worker's env and never has been. What the
 * intersection adds are the three things this config declares that the site's no
 * longer does: `ai`, `vectorize` and the test-only `CORPUS_REFRESH` var. A
 * dedicated typegen for this config would emit a second copy of the whole
 * runtime-types file and a second global `Env`, so this stays a one-line
 * intersection until there is a reason for it not to be.
 */
type McpEnv = Env & Pick<CorpusEnv, 'AI' | 'VECTORIZE' | 'CORPUS_REFRESH'>;

/**
 * The corpus job's view of this Worker, assembled explicitly rather than spread
 * from `env` -- `SITE` is not a binding and could not come from one.
 *
 * The site Worker used to hand `refreshCorpus` its own `ASSETS` binding. This
 * Worker has no assets, and giving it a copy of the site's would mean uploading
 * the whole site twice and rebuilding it before every MCP deploy, so the
 * documents are read over the public origin instead. `mcp.ryanlindsey.me` and
 * `ryanlindsey.me` are different hostnames on different Workers, so this is an
 * ordinary subrequest to the site rather than a fetch that could loop back into
 * this Worker.
 *
 * Wrapped in an arrow rather than passed as `{ fetch }`: global `fetch` is not
 * a method of anything here, and handing it over as a bare reference is the kind
 * of unbound-`this` hazard that costs an hour when it does bite.
 */
function corpusEnv(env: McpEnv): CorpusEnv {
  return {
    SITE: { fetch: (input, init) => fetch(input, init) },
    AI: env.AI,
    VECTORIZE: env.VECTORIZE,
    KV_CACHE: env.KV_CACHE,
    SITE_ORIGIN: env.SITE_ORIGIN,
    CORPUS_REFRESH: env.CORPUS_REFRESH,
  };
}

const INSTRUCTIONS = [
  "Ryan Lindsey's professional corpus, exposed as MCP tools.",
  'Public tools cover portfolio exploration. A private tier exists for scoped tokens;',
  'ask Ryan for access if you need it.',
].join(' ');

function createServer() {
  // `instructions` belongs to ServerOptions (the second argument), not to the
  // Implementation identity. Passing it here is also what puts it at the top
  // level of the initialize result, where the spec and clients look for it.
  // The `x-release-please-version` marker is load-bearing: release-please's `generic` updater
  // rewrites the semver on any line carrying it, which is what keeps the version this server
  // advertises over MCP in step with package.json. Moving the version off this line, or letting
  // a formatter split it across lines, silently strands it at whatever it says today.
  const server = new McpServer(
    { name: 'ryanlindsey-me', version: '1.4.1' }, // x-release-please-version
    { instructions: INSTRUCTIONS },
  );

  // No `inputSchema`: this tool takes no arguments, and the empty-object form
  // resolves to the deprecated raw-shape overload. Day 4 adds zod schemas with
  // the first tool that takes arguments.
  server.registerTool(
    'get_contact',
    {
      description: 'How to reach Ryan Lindsey, and his working timezone.',
    },
    async () => ({
      content: [
        {
          type: 'text' as const,
          text: JSON.stringify(
            {
              email: 'hello@ryanlindsey.me',
              site: 'https://ryanlindsey.me',
              timezone: 'America/Los_Angeles',
            },
            null,
            2,
          ),
        },
      ],
    }),
  );

  return server;
}

export default {
  fetch(request, env, ctx) {
    return createMcpHandler(createServer, { route: '/mcp' })(request, env, ctx);
  },

  /**
   * The publishing corpus's embedding refresh (Task 15), on this Worker's own
   * daily cron (`triggers.crons` in wrangler.jsonc).
   *
   * It is here rather than on the site Worker because the `ai` binding it runs
   * on is always-remote to @cloudflare/vite-plugin, and its presence in the
   * site's config made `astro build` open a remote proxy session that
   * credential-free CI cannot authenticate. Nothing in CI builds this Worker.
   * The pairing is not arbitrary either: day 4's semantic search runs over this
   * same index from this same Worker, so the Worker that queries the corpus is
   * the one that fills it.
   *
   * `waitUntil`, not `await`: the job outlives the handler's return, exactly as
   * the résumé-PDF job does on the site Worker.
   *
   * `corpusRefreshEnabled` is the test seam, not a feature flag: it reads a var
   * no deployed environment sets, so the deployed default is "run". See its doc
   * in src/lib/corpus.ts for why the harness turns it off rather than pointing
   * it at a stub -- short version, the harness's Vectorize is a local simulation
   * and a green run against one would prove nothing.
   */
  scheduled(_controller, env, ctx) {
    const corpus = corpusEnv(env);
    if (corpusRefreshEnabled(corpus)) ctx.waitUntil(refreshCorpus(corpus));
  },
} satisfies ExportedHandler<McpEnv>;
