/**
 * The site icon, in every format public/ ships (#363).
 *
 * The files are generated by scripts/icons.mjs and committed, so these assert
 * the committed bytes rather than rerunning the generator: a palette change in
 * src/styles/tokens.css that nobody reran the script for fails here, and so
 * does a hand edit that reintroduced live text or the handoff's metadata.
 */
import { readFileSync } from 'node:fs';
import { afterAll, beforeAll, expect, test } from 'vitest';
import { createTestHarness } from 'wrangler';
import { readTokens, requireTokens } from '../src/lib/tokens-read.mjs';
import { SITE_HARNESS_WORKERS } from './workers';
import { stripComments } from './markup';

const server = createTestHarness({ workers: SITE_HARNESS_WORKERS });

beforeAll(async () => {
  await server.listen();
});

afterAll(async () => {
  await server.close();
});

const publicFile = (name: string) => readFileSync(new URL(`../public/${name}`, import.meta.url));
const tokens = readTokens();

test('the token reader returns both palettes', () => {
  expect(tokens.light['--rl-bg']).toBe('#fafaf9');
  expect(tokens.dark['--rl-bg']).toBe('#0a0a0b');
  expect(tokens.dark['--rl-accent-ground']).toBe(tokens.light['--rl-accent-ground']);
});

/**
 * The token reader used to accept only lowercase six-digit hex, silently:
 * an uppercase value (which tests/tokens.test.ts's own regex accepts) simply
 * failed the reader's capture group and the token vanished from the returned
 * object rather than raising anything, reaching loadCardAssets and
 * scripts/icons.mjs as `undefined`. These three pin the reader's own
 * contract with synthetic CSS, independent of what src/styles/tokens.css
 * happens to hold today.
 */
test('an uppercase hex value is accepted, and lowercased', () => {
  const css = `:root { --rl-bg: #FAFAF9; }\n[data-theme='dark'] { --rl-bg: #0A0A0B; }`;
  expect(readTokens(css)).toEqual({
    light: { '--rl-bg': '#fafaf9' },
    dark: { '--rl-bg': '#0a0a0b' },
  });
});

test('a token value that is not a 6-digit hex color throws, naming the token', () => {
  const css = `:root { --rl-bg: red; }\n[data-theme='dark'] { --rl-bg: #0a0a0b; }`;
  expect(() => readTokens(css)).toThrow(/--rl-bg/);
});

test('requireTokens throws naming the missing key', () => {
  expect(() => requireTokens({ '--rl-bg': '#000000' }, ['--rl-bg', '--rl-ink'])).toThrow(
    /--rl-ink/,
  );
  expect(requireTokens({ '--rl-bg': '#000000' }, ['--rl-bg'])).toEqual({ '--rl-bg': '#000000' });
});

test.each([
  ['favicon-dark.svg', 'dark'],
  ['favicon-light.svg', 'light'],
] as const)('%s carries the current token values and outlined letters', (name, theme) => {
  const svg = publicFile(name).toString('utf8');
  expect(svg).toContain(`<rect width="64" height="64" fill="${tokens[theme]['--rl-bg']}"/>`);
  expect(svg).toContain(`d="M13 0h51v64H0V13z" fill="${tokens.dark['--rl-accent-ground']}"`);
  expect(svg).toMatch(new RegExp(`<path d="M[^"]+" fill="${tokens.dark['--rl-accent-on']}"/>`));
  expect(svg).not.toMatch(/<text\b/);
  expect(svg).not.toMatch(/c2pa/i);
  // XML forbids `--` inside a comment; a browser renders a malformed SVG icon as nothing.
  for (const [comment] of svg.matchAll(/<!--([\s\S]*?)-->/g)) {
    expect(comment.slice(4, -3)).not.toContain('--');
  }
});

test('the two variants differ in the notch and nothing else', () => {
  // Measured 2026-09-22: a blanket .replaceAll(bg, 'GROUND') over the whole
  // file is not safe here. tokens.css gives dark['--rl-bg'] and both themes'
  // --rl-accent-on the identical hex #0a0a0b, so that replace would also
  // clobber the ink comment and fill in the dark SVG while leaving the light
  // SVG's (differently hex'd) ink alone, failing this assertion on a token
  // coincidence that has nothing to do with the notch. Replacing the two full
  // lines the ground color actually appears on -- the per-theme comment and
  // the <rect> fill -- disambiguates it from the ink lines, which read "is
  // rl-accent-on" and "<path", never "is rl-bg" or "<rect", so this stays
  // exactly as strict: every other byte, ink included, must still match
  // verbatim.
  const normalize = (name: string, theme: 'dark' | 'light') => {
    const bg = tokens[theme]['--rl-bg'];
    return publicFile(name)
      .toString('utf8')
      .replace(`<!-- ${bg} is rl-bg, ${theme} theme -->`, '<!-- GROUND is rl-bg, THEME theme -->')
      .replace(
        `<rect width="64" height="64" fill="${bg}"/>`,
        '<rect width="64" height="64" fill="GROUND"/>',
      );
  };
  expect(normalize('favicon-dark.svg', 'dark')).toBe(normalize('favicon-light.svg', 'light'));
});

test('favicon.ico holds a 16 and a 32 frame, both PNG', () => {
  const ico = publicFile('favicon.ico');
  expect(ico.readUInt16LE(2), 'type 1 is an icon').toBe(1);
  expect(ico.readUInt16LE(4), 'frame count').toBe(2);
  expect([ico.readUInt8(6), ico.readUInt8(22)]).toEqual([16, 32]);
  for (const entry of [6, 22]) {
    const offset = ico.readUInt32LE(entry + 12);
    expect(ico.subarray(offset + 1, offset + 4).toString('latin1')).toBe('PNG');
  }
});

test.each([
  ['apple-touch-icon.png', 180],
  ['icon-192.png', 192],
  ['icon-512.png', 512],
])('%s is a %ipx square PNG', (name, size) => {
  const png = publicFile(name);
  expect(png.subarray(1, 4).toString('latin1')).toBe('PNG');
  expect([png.readUInt32BE(16), png.readUInt32BE(20)]).toEqual([size, size]);
});

test('the manifest names icons that exist', () => {
  const manifest = JSON.parse(publicFile('manifest.webmanifest').toString('utf8'));
  expect(manifest.name).toBe('Ryan Lindsey');
  for (const icon of manifest.icons) {
    expect(() => publicFile(icon.src.slice(1))).not.toThrow();
  }
});

/**
 * A `<link>` pointing at a 404 is invisible to every other test in this
 * repository, so each file is fetched through the harness as well.
 */
test.each([
  ['/favicon.ico', /^image\/(x-icon|vnd\.microsoft\.icon)/],
  ['/favicon-dark.svg', /^image\/svg\+xml/],
  ['/favicon-light.svg', /^image\/svg\+xml/],
  ['/apple-touch-icon.png', /^image\/png/],
  ['/icon-192.png', /^image\/png/],
  ['/icon-512.png', /^image\/png/],
  ['/manifest.webmanifest', /^application\/manifest\+json/],
])('%s is served with a usable type and a day of cache', async (path, type) => {
  const response = await server.fetch(path);
  expect(response.status).toBe(200);
  expect(response.headers.get('content-type')).toMatch(type);
  expect(response.headers.get('cache-control')).toBe('public, max-age=86400');
});

test('the home page links the icon, the fallback, the touch icon and the manifest', async () => {
  const html = stripComments(await (await server.fetch('/')).text());
  expect(html).toContain('<link rel="icon" href="/favicon-dark.svg" type="image/svg+xml">');
  expect(html).toContain('<link rel="icon" href="/favicon.ico" sizes="32x32">');
  expect(html).toContain('<link rel="apple-touch-icon" href="/apple-touch-icon.png">');
  expect(html).toContain('<link rel="manifest" href="/manifest.webmanifest">');
});
