/**
 * The site icon, in every format public/ ships (#363).
 *
 * The files are generated by scripts/icons.mjs and committed, so these assert
 * the committed bytes rather than rerunning the generator: a palette change in
 * src/styles/tokens.css that nobody reran the script for fails here, and so
 * does a hand edit that reintroduced live text or the handoff's metadata.
 */
import { readFileSync } from 'node:fs';
import { afterAll, beforeAll, expect, test } from 'vitest';
import { createTestHarness } from 'wrangler';
import { readTokens, requireTokens } from '../src/lib/tokens-read.mjs';
import { SITE_HARNESS_WORKERS } from './workers';
import { stripComments } from './markup';

const server = createTestHarness({ workers: SITE_HARNESS_WORKERS });

beforeAll(async () => {
  await server.listen();
});

afterAll(async () => {
  await server.close();
});

const publicFile = (name: string) => readFileSync(new URL(`../public/${name}`, import.meta.url));
const tokens = readTokens();

test('the token reader returns both palettes', () => {
  expect(tokens.light['--rl-bg']).toBe('#fafaf9');
  expect(tokens.dark['--rl-bg']).toBe('#0a0a0b');
  expect(tokens.dark['--rl-accent-ground']).toBe(tokens.light['--rl-accent-ground']);
});

/**
 * The token reader used to accept only lowercase six-digit hex, silently:
 * an uppercase value (which tests/tokens.test.ts's own regex accepts) simply
 * failed the reader's capture group and the token vanished from the returned
 * object rather than raising anything, reaching loadCardAssets and
 * scripts/icons.mjs as `undefined`. These three pin the reader's own
 * contract with synthetic CSS, independent of what src/styles/tokens.css
 * happens to hold today.
 */
test('an uppercase hex value is accepted, and lowercased', () => {
  const css = `:root { --rl-bg: #FAFAF9; }\n[data-theme='dark'] { --rl-bg: #0A0A0B; }`;
  expect(readTokens(css)).toEqual({
    light: { '--rl-bg': '#fafaf9' },
    dark: { '--rl-bg': '#0a0a0b' },
  });
});

test('a token value that is not a 6-digit hex color throws, naming the token', () => {
  const css = `:root { --rl-bg: red; }\n[data-theme='dark'] { --rl-bg: #0a0a0b; }`;
  expect(() => readTokens(css)).toThrow(/--rl-bg/);
});

test('requireTokens throws naming the missing key', () => {
  expect(() => requireTokens({ '--rl-bg': '#000000' }, ['--rl-bg', '--rl-ink'])).toThrow(
    /--rl-ink/,
  );
  expect(requireTokens({ '--rl-bg': '#000000' }, ['--rl-bg'])).toEqual({ '--rl-bg': '#000000' });
});

const inkPattern = () => new RegExp(`<path d="([^"]+)" fill="${tokens.dark['--rl-ink']}"/>`);

test('favicon.svg carries the current token values and outlined letters', () => {
  const svg = publicFile('favicon.svg').toString('utf8');
  expect(svg).toContain(`d="M0 0h64v64H0z" fill="${tokens.dark['--rl-accent-ground']}"`);
  expect(svg).toMatch(inkPattern());
  expect(svg).not.toMatch(/<text\b/);
  expect(svg).not.toMatch(/c2pa/i);
  // XML forbids `--` inside a comment; a browser renders a malformed SVG icon as nothing.
  for (const [comment] of svg.matchAll(/<!--([\s\S]*?)-->/g)) {
    expect(comment.slice(4, -3)).not.toContain('--');
  }
});

/**
 * One square and one set of letters, and nothing else: no corner cut from the
 * square and no ground painted behind one. The chamfer's corner showed as
 * white or black in Safari's tab strip depending on the theme (2026-09-24),
 * and painting it per theme is what made two variants and a swap necessary.
 */
test('favicon.svg is a square and the letters', () => {
  const svg = publicFile('favicon.svg').toString('utf8');
  expect(svg).not.toMatch(/<rect\b/);
  expect(svg.match(/<path\b/g)).toHaveLength(2);
});

/**
 * The letter outline's extent, from its coordinates. The quadratic control
 * points are included, which for these two glyphs lands within a unit of the
 * true outline.
 */
const inkBox = () => {
  const ink = publicFile('favicon.svg').toString('utf8').match(inkPattern());
  const numbers = ink![1].match(/-?\d+(\.\d+)?/g)!.map(Number);
  const xs = numbers.filter((_, i) => i % 2 === 0);
  const ys = numbers.filter((_, i) => i % 2 === 1);
  return { x1: Math.min(...xs), x2: Math.max(...xs), y1: Math.min(...ys), y2: Math.max(...ys) };
};

/**
 * Legibility in a 16-point tab, pinned as a number. The letters stood 24 units
 * tall on the 64-unit square until 2026-09-24 and read as a smudge in Safari's
 * tab strip even on a 5K display; 36 filled the square too far.
 */
test('the letters stand between 28 and 34 units tall', () => {
  const { y1, y2 } = inkBox();
  expect(y2 - y1).toBeGreaterThanOrEqual(28);
  expect(y2 - y1).toBeLessThanOrEqual(34);
});

test('the letters sit in the middle of the square', () => {
  const { x1, x2, y1, y2 } = inkBox();
  expect(Math.abs((x1 + x2) / 2 - 32)).toBeLessThanOrEqual(1);
  expect(Math.abs((y1 + y2) / 2 - 32)).toBeLessThanOrEqual(1);
});

test('favicon.ico holds a 16 and a 32 frame, both PNG', () => {
  const ico = publicFile('favicon.ico');
  expect(ico.readUInt16LE(2), 'type 1 is an icon').toBe(1);
  expect(ico.readUInt16LE(4), 'frame count').toBe(2);
  expect([ico.readUInt8(6), ico.readUInt8(22)]).toEqual([16, 32]);
  for (const entry of [6, 22]) {
    const offset = ico.readUInt32LE(entry + 12);
    expect(ico.subarray(offset + 1, offset + 4).toString('latin1')).toBe('PNG');
  }
});

test.each([
  ['apple-touch-icon.png', 180],
  ['icon-192.png', 192],
  ['icon-512.png', 512],
])('%s is a %ipx square PNG', (name, size) => {
  const png = publicFile(name);
  expect(png.subarray(1, 4).toString('latin1')).toBe('PNG');
  expect([png.readUInt32BE(16), png.readUInt32BE(20)]).toEqual([size, size]);
});

test('the manifest names icons that exist', () => {
  const manifest = JSON.parse(publicFile('manifest.webmanifest').toString('utf8'));
  expect(manifest.name).toBe('Ryan Lindsey');
  for (const icon of manifest.icons) {
    expect(() => publicFile(icon.src.slice(1))).not.toThrow();
  }
});

/**
 * A `<link>` pointing at a 404 is invisible to every other test in this
 * repository, so each file is fetched through the harness as well.
 */
test.each([
  ['/favicon.ico', /^image\/(x-icon|vnd\.microsoft\.icon)/],
  ['/favicon.svg', /^image\/svg\+xml/],
  ['/apple-touch-icon.png', /^image\/png/],
  ['/icon-192.png', /^image\/png/],
  ['/icon-512.png', /^image\/png/],
  ['/manifest.webmanifest', /^application\/manifest\+json/],
])('%s is served with a usable type and a day of cache', async (path, type) => {
  const response = await server.fetch(path);
  expect(response.status).toBe(200);
  expect(response.headers.get('content-type')).toMatch(type);
  expect(response.headers.get('cache-control')).toBe('public, max-age=86400');
});

test('the home page links the icon, the fallback, the touch icon and the manifest', async () => {
  const html = stripComments(await (await server.fetch('/')).text());
  expect(html).toContain('<link rel="icon" href="/favicon.svg" type="image/svg+xml">');
  expect(html).toContain('<link rel="icon" href="/favicon.ico" sizes="32x32">');
  expect(html).toContain('<link rel="apple-touch-icon" href="/apple-touch-icon.png">');
  expect(html).toContain('<link rel="manifest" href="/manifest.webmanifest">');
});
