-- Chat transcripts (04 §1). Like 0001 and 0002, this schema is a published
-- governance artifact (06 §2): /ai-policy states what is stored and for how
-- long, so a change here is a change to a public document.
--
-- NUMBERED 0004, NOT 0003. The day-6 plan says 0003_chat.sql; day 5 took that
-- number for the grant_jti partial index between the plan being written and
-- being executed. Two files cannot share a prefix -- wrangler orders by it --
-- so the number moved and nothing else did.
--
-- THIRTY DAYS, and the cleanup that enforces it ships in the same task as the
-- table (src/lib/retention.ts). migrations/0002 recorded a retention window for
-- `fit_reports` that nothing enforced; a stated window with no job behind it is
-- a claim, and this is the migration that stops making that mistake twice.
--
-- WHAT IS STORED, deliberately: the visitor's question and the answer. 04 §1
-- requires transcript logging for eval mining and /ai-policy discloses it. What
-- is NOT stored: any identifier for the person. `session_id` is generated by
-- the browser to group a conversation and is not a credential and not stable
-- across visits; there is no IP column, no user agent, and no cookie anywhere
-- in this feature.
CREATE TABLE chat_turns (
  id                TEXT    PRIMARY KEY,
  session_id        TEXT    NOT NULL,
  created_at        TEXT    NOT NULL,
  question          TEXT    NOT NULL,
  answer            TEXT    NOT NULL,
  model             TEXT    NOT NULL,
  -- The numbered sources the answer was grounded on, exactly as the client was
  -- sent them. Stored so a transcript can be re-read against what the model was
  -- actually shown -- an answer without its evidence is unauditable a week later.
  sources_json      TEXT    NOT NULL,
  -- How many of those sources the answer cited, and how many `[n]` markers
  -- named a number that does not exist. A non-zero `invalid_citations` is the
  -- earliest fabrication signal this feature has, and it is the chat analogue
  -- of `fit_reports.citations_dropped`.
  cited             INTEGER NOT NULL,
  invalid_citations INTEGER NOT NULL,
  outcome           TEXT    NOT NULL,
  duration_ms       INTEGER NOT NULL,
  -- 'site' for a browser through /chat, 'direct' for a caller that posted to
  -- the endpoint itself. Worth telling apart for the same reason the fit client
  -- sets its own user agent: they are different audiences with different costs.
  surface           TEXT    NOT NULL
);

-- Retention deletes on created_at; /ops counts sessions over a rolling window.
CREATE INDEX idx_chat_turns_created_at ON chat_turns (created_at);
CREATE INDEX idx_chat_turns_session ON chat_turns (session_id, created_at);
