#!/usr/bin/env node
/**
 * Renders the résumé sheet to a PDF and records its golden text extraction
 * (issue #183, epic #180).
 *
 * WHY A SCRIPT AND NOT THE WORKER. src/lib/resume-pdf.ts renders at runtime
 * from a Browser Run binding, and the epic's argument for moving off it is that
 * the PDF is a pure function of the commit: every input is repo content, so
 * runtime rendering buys nothing and charges three things. It put the artifact
 * where no test can see it, which is how a contact-free PDF shipped and stayed
 * shipped. It introduced a deploy race that froze the live file. And it bills
 * browser-minutes for a document that changes a few times a year. This script
 * is the first half of the replacement; 05 moves it into GitHub Actions and
 * publishes to R2, and only 06 retires the runtime path.
 *
 * WHAT IT DOES. Serves the already-built `dist/client` on an ephemeral port,
 * drives a local headless Chrome over CDP, waits for `data-resume-ready`,
 * prints, stamps metadata with src/lib/resume-pdf-metadata.ts, and writes two
 * outputs: the PDF, which is gitignored because it belongs in R2, and the
 * golden extraction, which is committed because it is what review reads.
 *
 * THE BUILD IS NOT RUN HERE. `npm run resume:pdf` is `astro build && node
 * scripts/resume-sheet.mjs`, the same shape as `npm test`. That keeps the build
 * where a reader already looks for it, and lets CI (04) call this file directly
 * after the build it has already paid for rather than doing it twice.
 *
 * NO PUPPETEER. `@cloudflare/puppeteer` is a Workers client for a Browser Run
 * binding, not a local launcher, and it cannot drive a Chrome on this machine.
 * Adding `puppeteer` proper would pull a ~170 MB browser download into every
 * install of this repo to save perhaps eighty lines of CDP. The protocol below
 * is five commands.
 */
import { spawn } from 'node:child_process';
import { createServer } from 'node:http';
import { createReadStream } from 'node:fs';
import { mkdtemp, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { homedir, tmpdir } from 'node:os';
import { extname, join, normalize, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';
import { extractText, getDocumentProxy } from 'unpdf';
import { resumePdfMetadata, stampPdfMetadata } from '../src/lib/resume-pdf-metadata.ts';

const root = new URL('../', import.meta.url);

/**
 * The slashed spelling, deliberately. Measured through the harness on
 * 2026-09-15 and recorded in src/pages/resume.print.astro: that file emits
 * `dist/client/resume.print/index.html`, the slashed form answers 200, and the
 * bare `/resume.print` answers 307 to it. Pointing the renderer at the bare
 * form would pay for a redirect on every run.
 */
const PRINT_PATH = '/resume.print/';

/** What src/pages/resume.print.astro sets on <html> inside document.fonts.ready. */
const READY_ATTRIBUTE = 'data-resume-ready';

/**
 * Both outputs live in tests/fixtures/ because 04 reads both of them from
 * there: the golden is diffed and the PDF is what `pdfinfo`, `pdffonts` and
 * `qpdf --check` are pointed at. Keeping them adjacent is also the reason the
 * PDF needs its own `.gitignore` line -- anywhere under `dist/` would have been
 * ignored already, and would have put the artifact back out of reach of the
 * tests, which is the failure this epic exists to fix.
 *
 * NOT to be confused with tests/fixtures/resume-sheet-sample.pdf, which is
 * committed and belongs to #182: that one is a frozen Chrome render the
 * metadata stamper asserts against and must never be regenerated by this
 * script, or its tests would start agreeing with whatever today's Chrome emits.
 */
const PDF_OUTPUT = new URL('tests/fixtures/resume-sheet.pdf', root);
const GOLDEN_OUTPUT = new URL('tests/fixtures/resume-sheet.txt', root);

/**
 * The face the running foot draws in, read from node_modules rather than
 * committed as a base64 blob so the foot and the sheet cannot drift onto
 * different versions of the same font: a Fontsource bump moves both at once.
 * 400 is the weight `.docline` uses at the head of the sheet, which the foot
 * is the counterpart to.
 */
const FOOT_FONT = new URL(
  'node_modules/@fontsource/ibm-plex-mono/files/ibm-plex-mono-latin-400-normal.woff2',
  root,
);

/* -------------------------------------------------------------------------- *
 * Chrome
 * -------------------------------------------------------------------------- */

/**
 * `CHROME_PATH` first so a runner can name its own browser -- that is the
 * variable GitHub Actions' setup-chrome and browser-actions both export, and 05
 * relies on it. The rest are the install locations that actually occur: macOS
 * puts Chrome in either /Applications or ~/Applications depending on whether it
 * was installed for all users, and this machine has the second (measured
 * 2026-09-15, Chrome 152).
 */
function chromeCandidates() {
  return [
    process.env.CHROME_PATH,
    process.env.PUPPETEER_EXECUTABLE_PATH,
    '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
    join(homedir(), 'Applications/Google Chrome.app/Contents/MacOS/Google Chrome'),
    '/Applications/Chromium.app/Contents/MacOS/Chromium',
    '/usr/bin/google-chrome',
    '/usr/bin/google-chrome-stable',
    '/usr/bin/chromium',
    '/usr/bin/chromium-browser',
  ].filter(Boolean);
}

async function findChrome() {
  for (const candidate of chromeCandidates()) {
    try {
      if ((await stat(candidate)).isFile()) return candidate;
    } catch {
      // Not there. The next candidate is the whole recovery.
    }
  }
  throw new Error(
    `no Chrome found. Tried:\n  ${chromeCandidates().join('\n  ')}\n` +
      'Set CHROME_PATH to the binary to use.',
  );
}

/**
 * Launches headless Chrome on an ephemeral debugging port and resolves the
 * WebSocket endpoint it prints to stderr.
 *
 * Port 0 rather than a fixed port: two runs of this script, or a run alongside
 * a developer's own debugging session, must not collide. Chrome answers by
 * printing the port it actually took, which is the line parsed below.
 *
 * The user-data-dir is a fresh temp directory every time. Without it Chrome
 * attaches to the profile the human is browsing in, which means their
 * extensions, their cookies and their open tabs are all in the render.
 */
async function launchChrome(executable) {
  const profile = await mkdtemp(join(tmpdir(), 'resume-sheet-'));
  const child = spawn(
    executable,
    [
      '--headless=new',
      '--remote-debugging-port=0',
      `--user-data-dir=${profile}`,
      '--no-first-run',
      '--no-default-browser-check',
      '--disable-extensions',
      '--hide-scrollbars',
      // Print output is sRGB; letting Chrome adopt the display profile makes
      // the same commit render different bytes on different machines.
      '--force-color-profile=srgb',
      // GitHub's runners run as a user whose sandbox Chrome refuses to start
      // under. Only there: dropping the sandbox on a developer's own machine
      // to render a local file would be a real loss for no gain.
      ...(process.env.CI ? ['--no-sandbox'] : []),
    ],
    { stdio: ['ignore', 'ignore', 'pipe'] },
  );

  const endpoint = await new Promise((resolvePromise, rejectPromise) => {
    let stderr = '';
    const timer = setTimeout(() => {
      rejectPromise(new Error(`Chrome did not report a DevTools endpoint:\n${stderr}`));
    }, 30_000);

    child.stderr.on('data', (chunk) => {
      stderr += chunk;
      const match = stderr.match(/ws:\/\/[^\s]+/);
      if (match) {
        clearTimeout(timer);
        resolvePromise(match[0]);
      }
    });
    child.once('error', (error) => {
      clearTimeout(timer);
      rejectPromise(error);
    });
    child.once('exit', (code) => {
      clearTimeout(timer);
      rejectPromise(new Error(`Chrome exited with ${code} before listening:\n${stderr}`));
    });
  });

  return {
    endpoint,
    /*
     * The wait for `exit` before removing the profile is not politeness. Chrome
     * is still flushing its Default/ subtree when SIGTERM arrives, so removing
     * the directory straight after `kill()` loses the race and throws
     * ENOTEMPTY -- measured 2026-09-15 on the first run of this script, after
     * the PDF had already been rendered. The removal is also best-effort: a
     * temp directory that outlives one run is the operating system's problem,
     * and failing the render over it would throw away the artifact.
     */
    async close() {
      const exited = new Promise((resolvePromise) => child.once('exit', resolvePromise));
      child.kill();
      await exited;
      await rm(profile, { recursive: true, force: true }).catch(() => {});
    },
  };
}

/**
 * The smallest CDP client that does this job: correlate replies by id, route
 * events by method, and nothing else.
 *
 * `flatten: true` on the attach below is what lets one socket carry both the
 * browser session and the page session, distinguished by `sessionId`. The
 * alternative, a second WebSocket to the page target, is the older protocol
 * shape and buys nothing here.
 */
class Cdp {
  #socket;
  #nextId = 1;
  #pending = new Map();
  #listeners = new Set();

  constructor(socket) {
    this.#socket = socket;
    socket.addEventListener('message', (event) => {
      const message = JSON.parse(event.data);
      if (message.id !== undefined) {
        const entry = this.#pending.get(message.id);
        if (!entry) return;
        this.#pending.delete(message.id);
        if (message.error) entry.reject(new Error(`${entry.method}: ${message.error.message}`));
        else entry.resolve(message.result);
        return;
      }
      for (const listener of this.#listeners) listener(message);
    });
  }

  static async connect(endpoint) {
    const socket = new WebSocket(endpoint);
    await new Promise((resolvePromise, rejectPromise) => {
      socket.addEventListener('open', resolvePromise, { once: true });
      socket.addEventListener('error', () => rejectPromise(new Error('CDP socket failed')), {
        once: true,
      });
    });
    return new Cdp(socket);
  }

  send(method, params = {}, sessionId) {
    const id = this.#nextId++;
    return new Promise((resolvePromise, rejectPromise) => {
      this.#pending.set(id, { method, resolve: resolvePromise, reject: rejectPromise });
      this.#socket.send(JSON.stringify({ id, method, params, ...(sessionId && { sessionId }) }));
    });
  }

  /** Resolves on the next matching event. Registered before the command that causes it. */
  once(method, sessionId) {
    return new Promise((resolvePromise) => {
      const listener = (message) => {
        if (message.method !== method) return;
        if (sessionId && message.sessionId !== sessionId) return;
        this.#listeners.delete(listener);
        resolvePromise(message.params);
      };
      this.#listeners.add(listener);
    });
  }

  close() {
    this.#socket.close();
  }
}

/* -------------------------------------------------------------------------- *
 * Serving dist/client
 * -------------------------------------------------------------------------- */

const MIME = new Map(
  Object.entries({
    '.html': 'text/html; charset=utf-8',
    '.css': 'text/css; charset=utf-8',
    '.js': 'text/javascript; charset=utf-8',
    '.json': 'application/json; charset=utf-8',
    '.svg': 'image/svg+xml',
    '.woff2': 'font/woff2',
    '.woff': 'font/woff',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.webp': 'image/webp',
    '.avif': 'image/avif',
    '.ico': 'image/x-icon',
    '.xml': 'application/xml; charset=utf-8',
    '.txt': 'text/plain; charset=utf-8',
  }),
);

/**
 * A static server over the build output, not a stand-in for the Worker. The
 * sheet is a prerendered page whose only subresources are the stylesheet and
 * the fonts Vite fingerprinted next to it, so what the renderer needs is
 * exactly what `dist/client` holds. Booting the real Worker to fetch one static
 * document would drag in KV, R2 and a service binding to the MCP Worker, all of
 * which this page is indifferent to.
 *
 * `font-src` and friends do not apply: this never leaves the loopback
 * interface, and the port is ephemeral.
 */
async function serveDist() {
  const base = fileURLToPath(new URL('dist/client/', root));
  try {
    await stat(base);
  } catch {
    throw new Error(`no build output at ${base}. Run \`npm run build\` first.`);
  }

  const server = createServer((request, response) => {
    const pathname = decodeURIComponent(new URL(request.url, 'http://127.0.0.1').pathname);
    // Astro writes `foo/index.html` for a directory route, so a path ending in
    // `/` resolves to the index inside it.
    const relative = pathname.endsWith('/') ? `${pathname}index.html` : pathname;
    // Traversal guard. This serves a directory to a browser, and the fact that
    // the browser is one we launched is a reason to keep the guard cheap, not
    // a reason to skip it.
    const target = resolve(base, `.${normalize(relative)}`);
    if (target !== base && !target.startsWith(base.endsWith(sep) ? base : base + sep)) {
      response.writeHead(403).end();
      return;
    }
    const stream = createReadStream(target);
    stream.once('error', () => response.writeHead(404).end());
    stream.once('open', () => {
      response.writeHead(200, {
        'content-type': MIME.get(extname(target)) ?? 'application/octet-stream',
      });
      stream.pipe(response);
    });
  });

  await new Promise((resolvePromise) => server.listen(0, '127.0.0.1', resolvePromise));
  const { port } = server.address();
  return {
    origin: `http://127.0.0.1:${port}`,
    async close() {
      await new Promise((resolvePromise) => server.close(resolvePromise));
    },
  };
}

/* -------------------------------------------------------------------------- *
 * The running foot
 * -------------------------------------------------------------------------- */

/**
 * Chrome renders the header and footer in a SEPARATE DOCUMENT from the page. It
 * has no access to the page's stylesheet, so the mono face has to be inlined
 * here as a data URL or the foot silently falls back to a system serif.
 *
 * Measured 2026-09-15, as a controlled pair rather than an observation: this
 * render lists six faces and tests/fixtures/resume-sheet-sample.pdf, the same
 * page printed by #182 with no foot at all, lists the same five minus
 * `Times-Roman`. So the sixth entry is the foot document's, it appears whatever
 * the template asks for, and it is invisible on the page -- every glyph in the
 * foot draws in the embedded mono.
 *
 * The issue predicted that entry and warned 04's font assertion would have to
 * allow it rather than fail on it. Measurement softens that: `pdffonts` reports
 * the `Times-Roman` entry as `CID TrueType`, embedded and subset, exactly like
 * the other five. So "every face embeds as CID TrueType" holds uniformly and 04
 * needs no carve-out; what it must not assert is a count of five, or a font
 * list with no `Times-Roman` in it.
 *
 * Every value comes from the résumé record. No page on this site spells the
 * name into a document by hand, and a foot that did would be the same class of
 * defect as the keyword list #182 refused to hand-author.
 */
function footerTemplate(resume, fontBase64) {
  const { name, label, url } = resume.basics;
  const site = url.replace(/^https?:\/\//, '').replace(/\/$/, '');
  return `<style>
  @font-face {
    font-family: 'SheetMono';
    src: url(data:font/woff2;base64,${fontBase64}) format('woff2');
    font-weight: 400;
    font-style: normal;
  }
  /*
   * Chrome gives the foot document its own tiny default type and its own zero
   * margins, and lays it out across the full paper width rather than inside the
   * page box. So the size is set here explicitly, and the horizontal padding
   * repeats the 0.66in side margin from @page in src/styles/resume-sheet.css so
   * the foot lines up with the text column above it. Those two numbers are
   * coupled; changing one without the other puts the foot out of alignment and
   * nothing will say so.
   */
  .foot {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    width: 100%;
    box-sizing: border-box;
    padding: 0 0.66in;
    font-family: 'SheetMono', monospace;
    font-size: 6.8pt;
    line-height: 1;
    letter-spacing: 0.16em;
    text-transform: uppercase;
    /* #333333 is the print palette's mid value, the one .docline draws in. */
    color: #333333;
    -webkit-print-color-adjust: exact;
  }
</style>
<div class="foot">
  <span>${escapeHtml(name)} · ${escapeHtml(label)}</span>
  <span>${escapeHtml(site)}</span>
  <span><span class="pageNumber"></span> / <span class="totalPages"></span></span>
</div>`;
}

function escapeHtml(value) {
  return value.replace(
    /[&<>"]/g,
    (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[character],
  );
}

/* -------------------------------------------------------------------------- *
 * Rendering
 * -------------------------------------------------------------------------- */

async function render(cdp, url, footer) {
  const { targetId } = await cdp.send('Target.createTarget', { url: 'about:blank' });
  const { sessionId } = await cdp.send('Target.attachToTarget', { targetId, flatten: true });

  await cdp.send('Page.enable', {}, sessionId);
  await cdp.send('Runtime.enable', {}, sessionId);
  // Same as browserRenderer's emulateMediaType('print'): the ready attribute is
  // set inside document.fonts.ready, and which faces are "used" -- so which the
  // promise waits on -- depends on the media the page is laid out for.
  await cdp.send('Emulation.setEmulatedMedia', { media: 'print' }, sessionId);

  const loaded = cdp.once('Page.loadEventFired', sessionId);
  await cdp.send('Page.navigate', { url }, sessionId);
  await loaded;

  await waitForReady(cdp, sessionId);

  /*
   * NO `marginTop`/`marginBottom`/`marginLeft`/`marginRight`, and that is the
   * point of this call. src/styles/resume-sheet.css's @page rule carries the
   * asymmetric 0.56in / 0.66in / 0.72in box that the approved three-page render
   * was measured from, and its own comment predicts this collision: the runtime
   * renderer passes `preferCSSPageSize: true` AND a uniform 0.6in margin
   * object, which describes a different page box, and whichever loses moves the
   * layout silently. The margin object is the one that goes. The deeper bottom
   * margin is also what makes room for the running foot.
   */
  const { data } = await cdp.send(
    'Page.printToPDF',
    {
      printBackground: true,
      preferCSSPageSize: true,
      displayHeaderFooter: true,
      // Chrome draws its own date-and-title header unless it is given an empty
      // one. An empty string is ignored; a template with no ink is not.
      headerTemplate: '<span></span>',
      footerTemplate: footer,
    },
    sessionId,
  );

  await cdp.send('Target.closeTarget', { targetId });
  return new Uint8Array(Buffer.from(data, 'base64'));
}

/**
 * Polls for the attribute rather than racing the load event, for the reason
 * src/lib/resume-pdf.ts gives: `networkidle0` and `waitForFonts` are
 * heuristics, and the attribute is the only deterministic "actually painted"
 * signal the page offers. A blank or unstyled sheet is the documented top
 * failure of printing before webfonts land, and it is a failure that produces a
 * plausible-looking PDF rather than an error.
 */
async function waitForReady(cdp, sessionId) {
  const deadline = Date.now() + 30_000;
  const expression = `document.documentElement.hasAttribute(${JSON.stringify(READY_ATTRIBUTE)})`;
  while (Date.now() < deadline) {
    const { result } = await cdp.send(
      'Runtime.evaluate',
      { expression, returnByValue: true },
      sessionId,
    );
    if (result.value === true) return;
    await new Promise((resolvePromise) => setTimeout(resolvePromise, 100));
  }
  throw new Error(`[${READY_ATTRIBUTE}] never appeared; the sheet did not finish its fonts`);
}

/* -------------------------------------------------------------------------- *
 * The golden extraction
 * -------------------------------------------------------------------------- */

/**
 * WHY unpdf. It is pure JavaScript, so this file reproduces on a developer
 * machine and on a runner with no system dependency to install. Poppler does
 * the structural checks in 04 -- page geometry, font programs, annotations,
 * the tag tree -- and is installed in CI alone, because those checks are the
 * ones that genuinely need a C library.
 *
 * WHY A GOLDEN AT ALL. The epic opens with a PDF that shipped without an email
 * address, a phone number or a single profile link, and stayed shipped, because
 * the artifact lived where nothing could read it. Text a human can diff is the
 * cheapest instrument that would have caught it on the first pull request.
 *
 * NOTHING DERIVED FROM THE RUN GOES IN THE FILE -- no timestamp, no byte count,
 * no Chrome version. A golden that changes when nothing changed is a golden
 * nobody reads twice. The counts in the preamble are properties of the
 * document, so they hold still, and putting them at the top means a regression
 * in any of them shows up in the first lines of the diff rather than somewhere
 * in the middle of three pages of prose. Verified 2026-09-15: two consecutive
 * runs over an unchanged commit write byte-identical goldens.
 *
 * THE TRACKED TEXT COMES OUT SPACED, and it is left that way. Every string the
 * sheet sets with `letter-spacing` -- the document line, the label under the
 * name, the section headings, the dates, the field keys, the skill leads, the
 * foot -- reads back as `R Y A N  L I N D S E Y`, because pdf.js emits one text
 * item per positioned glyph and puts a space between them.
 *
 * That is pdf.js being stricter than the field, not the sheet being broken.
 * Measured the same day against poppler's `pdftotext`, which reads the same
 * bytes as `RÉSUMÉ · RYAN LINDSEY` and `SENIOR ENGINEERING MANAGER`, unspaced.
 * The one string both extractors break is the 58pt field-key column, where
 * `EMAIL` reads as `E MA I L` -- so the labels on the contact block are the
 * only text on the sheet a parser genuinely cannot recover, and the VALUES
 * beside them, which are what anything reading this document is after, come
 * back clean in both.
 *
 * Normalizing the spacing away here was the tempting alternative and is the
 * wrong one: a golden that post-processes its input can hide the regression it
 * exists to catch, and this one is committed precisely because nothing else in
 * the repository can see this artifact. Whoever writes 04 should assert on
 * values and on the untracked body text, never on a tracked string.
 */
async function goldenText(bytes) {
  // getDocumentProxy is handed a copy: pdf.js transfers the buffer it is given
  // and leaves the original detached, and these same bytes are written to disk
  // afterwards.
  const document_ = await getDocumentProxy(new Uint8Array(bytes));
  const { totalPages, text } = await extractText(document_, { mergePages: false });

  const pages = text.map((page) => page.replace(/[ \t]+$/gm, '').trim());
  const bullets = pages.join('\n').match(/•/g)?.length ?? 0;

  const lines = [
    'Résumé sheet · golden text extraction',
    '=====================================',
    '',
    'The text layer of tests/fixtures/resume-sheet.pdf as unpdf reads it, one',
    'section per page. Regenerate with `npm run resume:pdf`. This file is',
    'committed and the PDF beside it is not: the PDF belongs in R2, and this is',
    'what review reads.',
    '',
    'A diff here is a change to what the sheet SAYS. A sheet that still renders',
    'but has lost its contact block, or whose bullet markers no longer survive',
    'extraction into the text layer an ATS reads, shows up as a diff in these',
    'lines and nowhere else.',
    '',
    `Pages: ${totalPages}`,
    `Bullet markers: ${bullets}`,
    '',
  ];

  for (const [index, page] of pages.entries()) {
    lines.push(`--- page ${index + 1} of ${totalPages} ---`, '', page, '');
  }

  return { golden: `${lines.join('\n').trimEnd()}\n`, totalPages, bullets };
}

/* -------------------------------------------------------------------------- *
 * Main
 * -------------------------------------------------------------------------- */

async function main() {
  /*
   * Read with `yaml` rather than through astro:content, which is an Astro-only
   * virtual module that does not resolve in a plain node process -- the same
   * reason tests/resume-sheet.test.ts and tests/resume-pdf-metadata.test.ts
   * read it this way. Unvalidated here on purpose: `astro build` has already
   * parsed this file against `resumeSchema` by the time this script runs, so a
   * record that would fail the schema fails the build first, and a second copy
   * of the schema in this file would be the duplicate source of truth that
   * src/lib/resume.ts's header argues against.
   */
  const resume = parse(
    await readFile(new URL('src/content/resume/ryan-lindsey.yaml', root), 'utf8'),
  );

  const [chrome, site, footFont] = await Promise.all([
    findChrome(),
    serveDist(),
    readFile(FOOT_FONT).then((buffer) => buffer.toString('base64')),
  ]);

  const browser = await launchChrome(chrome);
  let bytes;
  try {
    const cdp = await Cdp.connect(browser.endpoint);
    try {
      bytes = await render(cdp, `${site.origin}${PRINT_PATH}`, footerTemplate(resume, footFont));
    } finally {
      cdp.close();
    }
  } finally {
    // Both, on every path. A leaked Chrome outlives the shell it was started
    // from and holds the temp profile open behind it.
    await browser.close();
    await site.close();
  }

  const stamped = stampPdfMetadata(bytes, resumePdfMetadata(resume));
  const { golden, totalPages, bullets } = await goldenText(stamped);

  await writeFile(PDF_OUTPUT, stamped);
  await writeFile(GOLDEN_OUTPUT, golden);

  const kb = (stamped.byteLength / 1024).toFixed(1);
  console.log(`${fileURLToPath(PDF_OUTPUT)}  ${totalPages} pages, ${kb} KB`);
  console.log(`${fileURLToPath(GOLDEN_OUTPUT)}  ${bullets} bullet markers`);
}

await main();
